version: "3.9"

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always

    # Set root password
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=serverconf
      - MARIADB_USER=dbuser
      - MARIADB_PASSWORD=db3213

    # Expose the MySQL port
    ports:
      - "3306:3306"

    # Mount our init scripts
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - /data/db:/var/lib/mysql

  aidb:
    image: aidb:latest
    container_name: aidb
    restart: always
    working_dir: /home/work/aidb
    volumes:
      - ./src:/home/work/aidb
    ports:
      - "5000:5000"
    command: python web_server.py
